
// AutoGenerated File 
// Version: 2020.5.6.1
// ReleaseDate: 5/6/2020 3:32:51 PM
namespace Resources
{
    using System;
    using Content.Localization;
    public static class OurTest
    {
        public static IContentLocalizer Content { get; set; }
        public static string DropDown => Content["DropDown"];
        public static string Number => Content["Number"];
        public static string DateField => Content["DateField"];
        public static string Decimal => Content["Decimal"];
        public static string ImageTest => Content["ImageTest"];
        public static string Widget => Content["Widget"];
        public static string Banner => Content["Banner"];
        public static string TextSample => Content["TextSample"];
        public static string CheckBox => Content["CheckBox"];

        [Obsolete("Use Content[name] instead")]
        public static string GetObject(string name)
        {
            return Content[name];
        } 
    }
}