using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Content.Localization
{
    public class StaticContentClassGenerator : IContentClassGenerator
    {
        private readonly ClassGeneratorOptions _options;

        public StaticContentClassGenerator(ClassGeneratorOptions options )
        {
            _options = options;
        }

        public string GetFullFileName()
        {
            return Path.Combine(_options.Location, _options.ClassName + ".cs");
        }

        public string Generate(ContentVersion version, IEnumerable<ContentItem> items)
        {
            if (items is null)
            {
                throw new ArgumentNullException(nameof(items));
            }

            var sb = new StringBuilder();
            sb.Append($@"
// AutoGenerated File 
// Version: {version?.Version}
// ReleaseDate: {version?.ReleaseDate}
namespace {_options.Namespace}
{{
    using System;
    using Content.Localization;
    public static class {_options.ClassName}
    {{
        public static IContentLocalizer Content {{ get; set; }}
");
            foreach (var item in items.Where(o=>o.Name!="Content"))
            {
                sb.AppendLine(
                    !item.Value.Contains("<exigocarousel>")
                        ? $"        public static string {item.Name} => Content[\"{item.Name}\"];"
                        : StubCarousel(item, items));
            }

            sb.Append($@"
        [Obsolete(""Use Content[name] instead"")]
        public static string GetObject(string name)
        {{
            return Content[name];
        }} 
    }}
}}");
            return sb.ToString();
        }

        public static readonly Dictionary<string, string> DataSetIdentifiers = new Dictionary<string, string>
        {
            {"Ranks", "rankID"},
            {"CustomerTypes", "customerType"}
        };

        private static string StubCarousel(ContentItem carousel, IEnumerable<ContentItem> resourceItems)
        {
            var uniqueParams = new List<string>();
            foreach (Match bannerName in new Regex("(?<=<exigobanner name=\").*?(?=\" />)").Matches(
                carousel.Value))
            foreach (Match setName in new Regex("(?<=<dataset name=\").*?(?=\" />)").Matches(resourceItems
                .FirstOrDefault(b => b.Name == bannerName.Value).Value))
            {
                var first = resourceItems.FirstOrDefault(d => d.Name == setName.Value);
                if (first != null && DataSetIdentifiers.ContainsKey(first.Value.Split(':')[0]) &&
                    !uniqueParams.Contains(DataSetIdentifiers[first.Value.Split(':')[0]]))
                    uniqueParams.Add(DataSetIdentifiers[first.Value.Split(':')[0]]);
            }

            return
                $@"        public static string {carousel.Name} ({(uniqueParams.Count > 0 ? "string" : "")} {string.Join(" = null,", uniqueParams).Replace(",", ",string ")} {(uniqueParams.Count > 0 ? "= null" : "")}) {{ 
                return Content.GenerateCarousel(""{carousel.Name}"", {CreateDictionaryParams(uniqueParams)}); 
        }} {Environment.NewLine}";
        }

        private static string CreateDictionaryParams(IReadOnlyCollection<string> filters)
        {
            var filterString = new StringBuilder(" new Dictionary<string,string>() {");

            foreach (var filter in filters)
                filterString.Append($"{{\"{KeyOfValue(filter)}\", {filter}}},");

            return (filters.Count > 0
                       ? filterString.ToString().Substring(0, filterString.Length - 1)
                       : filterString.ToString()) + "}";
        }

        private static string KeyOfValue(string val)
        {
            foreach (var i in DataSetIdentifiers)
                if (i.Value == val)
                    return i.Key;

            return null;
        }


        public async Task<ContentVersion> GetExistingVersionAsync()
        {
            FileInfo fi = new FileInfo(GetFullFileName());
            if (!fi.Exists)
                return null;

            var version = new ContentVersion();

            using var reader = fi.OpenText();

            for (int i = 0; i < 5; i++)
            {
                var line = await reader.ReadLineAsync().ConfigureAwait(false);

                if (line==null)
                    break;

                var versionSearch       = "// Version: ";
                var dateSearch          = "// ReleaseDate: ";

                if (line.StartsWith(versionSearch, StringComparison.InvariantCulture))
                    version.Version     = line.Substring(versionSearch.Length);
                
                if (line.StartsWith(dateSearch, StringComparison.InvariantCulture))
                    version.ReleaseDate = DateTime.Parse(line.Substring(dateSearch.Length), CultureInfo.InvariantCulture);
            }

            return version;
        }



        public async Task GenerateAndSaveIfChangedAsync(ContentVersion version, IContentSource contentSource)
        {
            if (contentSource is null)
            {
                throw new ArgumentNullException(nameof(contentSource));
            }

            var existing = await GetExistingVersionAsync()
                .ConfigureAwait(false);

            if (existing?.Version != version?.Version || existing?.ReleaseDate?.ToString(CultureInfo.InvariantCulture) != version?.ReleaseDate?.ToString(CultureInfo.InvariantCulture))
            {
                if (!Directory.Exists(_options.Location))
                    Directory.CreateDirectory(_options.Location);

                File.WriteAllText(GetFullFileName(), 
                    Generate(version, 
                        await contentSource.GetAllContentItemsAsync(_options.DefaultCultureCode, null)
                            .ConfigureAwait(false)));
            }
        }
    }
}
